appName: WebScraping

databases:
  mysql:
        host: localhost
        port: 3306
        user: root
        passwd: 1q2w3e4r
        db: crawler_data
        raise_on_warnings: True
        use_pure: False
        autocommit: True
        pool_size: 5
        connection_timeout: 180
  other:
      preprocessing_queue:
          - preprocessing.scale_and_center
          - preprocessing.dot_reduction
          - preprocessing.connect_lines
      use_anonymous: yes
